export const LANG_OPTIONS = [
  { value:'en', label:'EN', flag:'🇬🇧' },
  { value:'it', label:'IT', flag:'🇮🇹' },
  { value:'de', label:'DE', flag:'🇩🇪' },
  { value:'es', label:'ES', flag:'🇪🇸' },
  { value:'fr', label:'FR', flag:'🇫🇷' },
  { value:'pt', label:'PT', flag:'🇵🇹' },
];
export const UI_T = {
  en: { home:'Home', exams:'Exams', flash:'Flash', flashcards:'Flashcards', quiz:'Quiz', stats:'Stats', dashboard:'Dashboard', myExams:'My Exams', calendar:'Calendar', aiTutor:'AI Tutor', analytics:'Analytics', goodMorning:'Good morning', ready:'Ready to continue your learning journey?', todaySchedule:'Today schedule', dailyTasks:'Daily tasks', recommended:'Recommended today', openCalendar:'Open Calendar', examSub:'Your exams and study materials', newExam:'New Exam', studyPlan:'Study Plan', searchExams:'Search exams...', signOut:'Sign out' },
  it: { home:'Home', exams:'Esami', flash:'Flash', flashcards:'Flashcards', quiz:'Quiz', stats:'Stats', dashboard:'Dashboard', myExams:'I miei esami', calendar:'Calendario', aiTutor:'AI Tutor', analytics:'Analytics', goodMorning:'Buongiorno', ready:'Pronto a continuare il tuo percorso?', todaySchedule:'Programma di oggi', dailyTasks:'Task del giorno', recommended:'Consigliati oggi', openCalendar:'Apri Calendario', examSub:'I tuoi esami e materiali di studio', newExam:'Nuovo esame', studyPlan:'Piano studio', searchExams:'Cerca esami...', signOut:'Esci' },
  de: { home:'Home', exams:'Prüfungen', flash:'Flash', flashcards:'Karten', quiz:'Quiz', stats:'Stats', dashboard:'Dashboard', myExams:'Meine Prüfungen', calendar:'Kalender', aiTutor:'AI Tutor', analytics:'Analytics', goodMorning:'Guten Morgen', ready:'Bereit, weiterzulernen?', todaySchedule:'Heutiger Plan', dailyTasks:'Tagesaufgaben', recommended:'Heute empfohlen', openCalendar:'Kalender öffnen', examSub:'Deine Prüfungen und Lernmaterialien', newExam:'Neue Prüfung', studyPlan:'Lernplan', searchExams:'Prüfungen suchen...', signOut:'Abmelden' },
  es: { home:'Inicio', exams:'Exámenes', flash:'Flash', flashcards:'Tarjetas', quiz:'Quiz', stats:'Stats', dashboard:'Dashboard', myExams:'Mis exámenes', calendar:'Calendario', aiTutor:'Tutor IA', analytics:'Analíticas', goodMorning:'Buenos días', ready:'¿Listo para seguir aprendiendo?', todaySchedule:'Programa de hoy', dailyTasks:'Tareas del día', recommended:'Recomendado hoy', openCalendar:'Abrir calendario', examSub:'Tus exámenes y materiales de estudio', newExam:'Nuevo examen', studyPlan:'Plan de estudio', searchExams:'Buscar exámenes...', signOut:'Salir' },
  fr: { home:'Accueil', exams:'Examens', flash:'Flash', flashcards:'Cartes', quiz:'Quiz', stats:'Stats', dashboard:'Dashboard', myExams:'Mes examens', calendar:'Calendrier', aiTutor:'Tuteur IA', analytics:'Analytics', goodMorning:'Bonjour', ready:'Prêt à continuer ton apprentissage ?', todaySchedule:'Planning du jour', dailyTasks:'Tâches du jour', recommended:'Recommandé aujourd’hui', openCalendar:'Ouvrir le calendrier', examSub:'Tes examens et supports de révision', newExam:'Nouvel examen', studyPlan:'Plan de révision', searchExams:'Rechercher des examens...', signOut:'Déconnexion' },
  pt: { home:'Início', exams:'Exames', flash:'Flash', flashcards:'Flashcards', quiz:'Quiz', stats:'Stats', dashboard:'Dashboard', myExams:'Meus exames', calendar:'Calendário', aiTutor:'Tutor IA', analytics:'Analytics', goodMorning:'Bom dia', ready:'Pronto para continuar a aprender?', todaySchedule:'Agenda de hoje', dailyTasks:'Tarefas do dia', recommended:'Recomendado hoje', openCalendar:'Abrir calendário', examSub:'Os teus exames e materiais de estudo', newExam:'Novo exame', studyPlan:'Plano de estudo', searchExams:'Procurar exames...', signOut:'Sair' },
};
export function tt(lang, key) { return (UI_T[lang] && UI_T[lang][key]) || UI_T.en[key] || key; }
