export const homeS = {
  wrap: { width: '100%', maxWidth: '100%', minWidth: 0, overflowX: 'hidden' },
  h1: { margin: 0, fontSize: 26, fontWeight: 700, letterSpacing: '-0.02em', color: 'var(--ink)' },
  sub: { margin: '6px 0 0', color: 'var(--gray)', fontSize: 15 },
  scheduleCard: { width: '100%', maxWidth: '100%', minWidth: 0, boxSizing: 'border-box', overflow: 'hidden', background:'var(--clay-surface)', border:'1px solid rgba(255,255,255,.74)', borderRadius:26, marginBottom:24, boxShadow:'var(--clay-shadow), var(--clay-highlight)' },
  scheduleHead: { display:'flex', alignItems:'center', gap:10, marginBottom:18, width:'100%', minWidth:0 },
  scheduleTitle: { margin:0, minWidth:0, fontSize:16, fontWeight:700, color:'var(--ink)', lineHeight:1.25 },
  sectionLabel: { margin: '0 0 12px', fontSize: 15, fontWeight: 700, color: 'var(--ink)' },
  cardsRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 20 },
  bigCard: { border: '1px solid rgba(255,255,255,.74)', borderRadius: 26, padding: 22, display: 'flex', flexDirection: 'column', gap: 10, background:'var(--clay-surface)', boxShadow:'var(--clay-shadow-sm)' },
  dot: { width: 22, height: 22, borderRadius: 999, boxShadow: '0 0 0 6px var(--dot-glow,rgba(255,255,255,.6))' },
  cardTitle: { margin: '6px 0 2px', fontSize: 18, fontWeight: 700, color: 'var(--ink)' },
  cardMeta: { margin: 0, color: 'var(--gray)', fontSize: 13 },
  primaryBtn: { marginTop: 14, padding: '11px 16px', borderRadius: 16, background: 'linear-gradient(145deg,var(--indigo),var(--purple))', color: '#fff', fontWeight: 800, fontSize: 14, width: '100%', boxShadow:'12px 16px 30px -18px rgba(76,59,255,.78)' },
  outlineBtn: { marginTop: 14, padding: '11px 16px', borderRadius: 16, background: 'linear-gradient(145deg,#FFFFFF,#F2ECFF)', color: 'var(--ink)', border: '1px solid rgba(255,255,255,.74)', fontWeight: 800, fontSize: 14, width: '100%', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6, boxShadow:'var(--clay-shadow-sm)' },
  recoBadge: { fontSize:12, padding:'3px 10px', borderRadius:999, fontWeight:700 },
  recoDoneCard: { background:'linear-gradient(180deg,#F0FDF4 0%,#FFFFFF 100%)', borderColor:'#86efac', boxShadow:'0 18px 45px -34px rgba(16,185,129,.6)' },
  doneDot: { background:'#10B981', display:'grid', placeItems:'center', boxShadow:'0 0 0 10px rgba(16,185,129,.1)' },
  doneBadge: { fontSize:12, padding:'5px 12px', borderRadius:999, fontWeight:800, letterSpacing:'-.01em' },
  doneBtn: { marginTop:14, padding:'11px 16px', borderRadius:999, background:'#ECFDF5', color:'#047857', border:'1.5px solid #A7F3D0', fontWeight:800, fontSize:14, width:'100%', display:'inline-flex', alignItems:'center', justifyContent:'center', gap:6 },
  assistant: { background: 'var(--clay-tint)', borderRadius: 26, padding: 22, border: '1px solid rgba(255,255,255,.72)', display: 'flex', flexDirection: 'column', boxShadow:'var(--clay-shadow-sm)' },
  assistantIcon: { width: 38, height: 38, borderRadius: 999, background: 'var(--assistant-icon-bg)', color: 'var(--indigo)', display: 'grid', placeItems: 'center' },
  assistantTitle: { margin: 0, fontSize: 15, fontWeight: 700, color: 'var(--ink)' },
  assistantSub: { margin: '2px 0 0', color: 'var(--gray)', fontSize: 13 },
  msgUser: { padding: '12px 16px', background: 'var(--surface)', borderRadius: 14, border: '1px solid var(--border)', color: 'var(--ink)', fontSize: 14 },
  msgAI:   { padding: '12px 16px', background: 'var(--teal)', borderRadius: 14, color: 'var(--ink)', fontSize: 14 },
};
